"""Cross-check that every env var named in compose has an .env.example entry,
and every example entry is referenced by at least one service."""
from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
COMPOSE_FILE = REPO_ROOT / "infra" / "docker-compose.yml"
ENV_EXAMPLE = REPO_ROOT / "infra" / ".env.example"

# Variables Compose evaluates from the host shell (not infra/.env), or that
# we deliberately don't document because they're stable per-deployment.
_NOT_IN_EXAMPLE_OK = {
    "MEMEX_CAPTURE_TOKEN_telegram",  # generated by bootstrap, has comment in example
}

# Compose-internal pseudo-vars that aren't user-facing.
_IGNORE_VARS = {"COMPOSE_PROJECT_NAME"}

# .env.example keys that exist as commented-out optional examples.
_OPTIONAL_EXAMPLE_KEYS = {"MEMEX_CAPTURE_TOKEN_devbox"}


def _compose_referenced_vars() -> set[str]:
    text = COMPOSE_FILE.read_text()
    # Match ${VAR} and ${VAR:-default}.
    refs = set(re.findall(r"\$\{([A-Za-z_][A-Za-z0-9_]*)(?::-[^}]*)?\}", text))
    return refs - _IGNORE_VARS


def _example_keys() -> set[str]:
    keys: set[str] = set()
    for line in ENV_EXAMPLE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            keys.add(line.split("=", 1)[0].strip())
    return keys


def _example_keys_including_commented() -> set[str]:
    keys: set[str] = set()
    for raw in ENV_EXAMPLE.read_text().splitlines():
        line = raw.strip()
        # Allow a `#` followed by an env-style key=value as a documented optional.
        m = re.match(r"^#\s*([A-Za-z_][A-Za-z0-9_]*)\s*=", line)
        if m:
            keys.add(m.group(1))
        elif "=" in line and not line.startswith("#"):
            keys.add(line.split("=", 1)[0].strip())
    return keys


def test_every_referenced_var_is_documented():
    referenced = _compose_referenced_vars()
    documented = _example_keys() | _OPTIONAL_EXAMPLE_KEYS
    missing = referenced - documented - _NOT_IN_EXAMPLE_OK
    # MEMEX_CAPTURE_TOKEN_telegram has a documented comment line but its
    # *generated* form is what bootstrap writes; allowlist it explicitly.
    assert not missing, f"compose references undocumented vars: {sorted(missing)}"


def test_every_documented_var_is_used_or_intentional():
    referenced = _compose_referenced_vars()
    documented = _example_keys_including_commented()
    # MEMEX_CAPTURE_TOKEN_telegram is loaded via env_file at runtime by the
    # capture API rather than referenced by ${...} interpolation; same for
    # the optional MEMEX_CAPTURE_TOKEN_devbox example. Both are intentional.
    intentional = {"MEMEX_CAPTURE_TOKEN_telegram", "MEMEX_CAPTURE_TOKEN_devbox"}
    extra = documented - referenced - intentional
    assert not extra, f".env.example documents unused vars: {sorted(extra)}"


def test_capture_api_token_label_matches_bot_token_var():
    """The bot's MEMEX_CAPTURE_API_TOKEN must be wired to MEMEX_CAPTURE_TOKEN_telegram.

    This is what makes queue.submitter read 'api:telegram' (Phase 1 tracker note).
    """
    text = COMPOSE_FILE.read_text()
    # Look for the literal interpolation in the telegram_bot environment block.
    assert (
        "MEMEX_CAPTURE_API_TOKEN: \"${MEMEX_CAPTURE_TOKEN_telegram}\"" in text
    ), "bot's capture token must be sourced from MEMEX_CAPTURE_TOKEN_telegram"
